[gtest] Adapted tests to docker-compose

diff --git a/demo_cpp_hello_world/Makefile b/demo_cpp_hello_world/Makefile
--- a/demo_cpp_hello_world/Makefile
+++ b/demo_cpp_hello_world/Makefile
@@ -50,6 +50,10 @@ docker_client:build
 	cp build_debian/greeter_sync_client docker_sync_client/.
 	cd docker_sync_client && docker build . -t docker_sync_client && rm greeter_sync_client && cd ..
 
+docker_test:build
+	cp build_debian/test_server docker_sync_test/.
+	cd docker_sync_test && docker build . -t docker_sync_test && rm test_server && cd ..
+
 docker_images:docker_server docker_client
 	echo "Deploying server and client"
 
@@ -66,10 +70,24 @@ dc_test:docker_images
 	       else echo "Failure" && docker-compose logs client; \
 	       fi
 
+dc_gtest: docker_server docker_test
+	cd compose_test && docker-compose up --force-recreate -d
+	cd compose_test && docker-compose logs -t
+	cd compose_test && \
+	    result=`docker-compose ps | grep test | grep "Exit 0"` || true && \
+	    echo "$${result}" && \
+	    if [ -n "$${result}" ]; \
+	       then echo "Success"; \
+	       else echo "Failure" && docker-compose logs test; \
+	       fi
+
 dc_stop_demo:
 	cd compose_demo && docker-compose stop && docker-compose down && cd ..
 
-dc_stop: dc_stop_demo
+dc_stop_test:
+	cd compose_test && docker-compose stop && docker-compose down && cd ..
+
+dc_stop: dc_stop_demo dc_stop_test
 	echo "Stopping docker compose"
 
 dc_clean: dc_stop
@@ -214,12 +232,3 @@ run_async_client_debug: run_async_server
 	                        --ip `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' grpc_async_server` \
 	                        --port 50053"
 	        #/bin/sh -c "export GRPC_TRACE=all && export GRPC_VERBOSITY=DEBUG && ./greeter_async_client"
-
-test_sync_server: build run_sync_server
-	docker run \
-	        --rm \
-	        -v $(shell pwd):/shared \
-	        -u $(shell id -u):$(shell id -g) \
-	        -w /shared/build_debian \
-	        debian_grpc \
-	        ./test_server --gtest_color=yes
