[compose] Added docker-compose to demo_wave_cpp

diff --git a/demo_cpp_wave/Makefile b/demo_cpp_wave/Makefile
--- a/demo_cpp_wave/Makefile
+++ b/demo_cpp_wave/Makefile
@@ -1,28 +1,16 @@
 .PHONY: all build cmake stop test
 
-all: build
+# make dc_test -> performs grpc test with docker-compose, it will
+#                 create docker base image
+#                 build executables in the build directory,
+#                 create docker deployment images,
+#                 setup docker compose in detached mode,
+#                 wait for client to end up,
+#                 check for client return code
+#
+# make dc_clean -> deletes build directory and deletes docker images
 
-test: build run_wave_client stop
-	@echo "Building app, building network, running server, and running client"
-
-clean: stop
-	rm -rf build_debian binMSVC
-
-cwd := $(shell pwd)
-archive:
-	echo $(cwd) && \
-	echo $(shell basename $(cwd)) && \
-	cd .. && \
-	tar -zcf GRPC_demo.tgz \
-	    --exclude='$(shell basename $(cwd))/build*' \
-	    --exclude='$(shell basename $(cwd))/binMSVC' \
-	    --exclude='$(shell basename $(cwd))/.vscode' \
-	    --exclude='$(shell basename $(cwd))/report*' \
-	    $(shell basename $(cwd)) && \
-	cd $(cwd)
-
-build: cmake
-	docker run --rm -v $(shell pwd):/shared -u $(shell id -u):$(shell id -g) -w /shared/build_debian debian_grpc ninja
+all: dc_test
 
 cmake:
 	docker build -t debian_grpc .
@@ -34,69 +22,38 @@ cmake:
 	          -DCMAKE_INSTALL_PREFIX:PATH=/opt/grpc_demo \
 	          /shared
 
-network:
-	if docker network list | grep grpc_net > /dev/null ; then echo ""; else docker network create grpc_net; fi;
+build: cmake
+	docker run --rm -v $(shell pwd):/shared -u $(shell id -u):$(shell id -g) -w /shared/build_debian debian_grpc ninja
 
-run_wave_server:network
-	@if docker ps | grep grpc_wave_server > /dev/null ; \
-	    then \
-	    echo ""; \
-	    else \
-	    echo "Launching wave server" && \
-	        docker run -d \
-	        --net=grpc_net \
-	        --name grpc_wave_server \
-	        -p 50051:50051 \
-	        --rm \
-	        -v $(shell pwd):/shared \
-	        -u $(shell id -u):$(shell id -g) \
-	        -w /shared/build_debian \
-	        debian_grpc \
-	        ./wave_server; \
-	    fi;
+docker_server:build
+	cp build_debian/wave_server docker_wave_server/.
+	cd docker_wave_server && docker build . -t docker_wave_server && rm wave_server && cd ..
 
-run_wave_client:run_wave_server
-	docker run \
-	    --net=grpc_net \
-	    --name grpc_wave_client \
-	    -p 50052:50052 \
-	    --rm \
-	    -v $(shell pwd):/shared \
-	    -u $(shell id -u):$(shell id -g) \
-	    -w /shared/build_debian debian_grpc \
-	    ./wave_client \
-	    --ip `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' grpc_wave_server` \
-	    --port 50051
+docker_client:build
+	cp build_debian/wave_client docker_wave_client/.
+	cd docker_wave_client && docker build . -t docker_wave_client && rm wave_client && cd ..
 
-run_wave_client_debug:run_wave_server
-	docker run \
-	    --net=grpc_net \
-	    --name grpc_wave_client \
-	    -p 50052:50052 \
-	    --rm \
-	    -v $(shell pwd):/shared \
-	    -u $(shell id -u):$(shell id -g) \
-	    -w /shared/build_debian debian_grpc \
-	    /bin/sh -c "export GRPC_VERBOSITY=DEBUG && \
-	                ./wave_client \
-	                    --ip `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' grpc_wave_server` \
-	                    --port 50051"
-	    #/bin/sh -c "export GRPC_TRACE=all && export GRPC_VERBOSITY=DEBUG && ./greeter_wave_client"
+docker_images:docker_server docker_client
+	echo "Deploying server and client"
 
-stop:
-	@if docker ps | grep grpc_wave_server > /dev/null ; then echo "Stopping grpc_wave_server" && docker rm -f grpc_wave_server; fi;
-	@if docker ps | grep grpc_wave_client > /dev/null ; then echo "Stopping grpc_wave_client" && docker rm -f grpc_wave_client; fi;
-	@if docker network list | grep grpc_net > /dev/null ; then echo "Deleting grpc_net" && docker network rm grpc_net; fi;
+dc_test:docker_images
+	cd compose_demo && docker-compose up --force-recreate -d
+	cd compose_demo && docker-compose logs -t
+	cd compose_demo && sleep 0.5 && \
+	    while [ -z "`docker-compose ps | grep client | grep Exit`" ]; do echo "Client terminated"; done
+	cd compose_demo && \
+	    result=`docker-compose ps | grep client | grep "Exit 0"` || true && \
+	    echo "$${result}" && \
+	    if [ -n "$${result}" ]; \
+	       then echo "Success"; \
+	       else echo "Failure" && docker-compose logs client; \
+	       fi
 
-inspect:
-	@if docker ps | grep grpc_wave_server > /dev/null ; \
-	    then \
-	    echo "Inspect grpc_wave_server" && docker inspect grpc_wave_server -f "{{json .NetworkSettings.Networks }}"; \
-	    fi;
+dc_stop_demo:
+	cd compose_demo && docker-compose stop && docker-compose down && cd ..
 
-get_server_ip_from_server:
-	@if docker ps | grep grpc_wave_server > /dev/null ; \
-	    then \
-	    echo "Inspect grpc_wave_server" && \
-	    docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' grpc_wave_server; \
-	    fi;
+dc_stop:dc_stop_demo
+	echo "Stopping docker compose"
+
+dc_clean:dc_stop
+	docker rmi -f docker_wave_server docker_wave_client
