[ghz] Added ghz performance test

diff --git a/demo_cpp_wave/Makefile b/demo_cpp_wave/Makefile
--- a/demo_cpp_wave/Makefile
+++ b/demo_cpp_wave/Makefile
@@ -8,6 +8,8 @@
 #                 wait for client to end up,
 #                 check for client return code
 #
+# make dc_perf -> performs grpc test with docker-compose and ghz
+#
 # make dc_clean -> deletes build directory and deletes docker images
 
 all: dc_test
@@ -48,6 +50,9 @@ docker_test:build
 	cp build_debian/wave_test docker_wave_test/.
 	cd docker_wave_test && docker build . -t docker_wave_test && rm wave_test && cd ..
 
+docker_ghz:
+	cd docker_wave_ghz && docker build . -t docker_wave_ghz && cd ..
+
 docker_images:docker_server docker_client
 	echo "Deploying server and client"
 
@@ -75,14 +80,31 @@ dc_gtest:docker_server docker_test
 	       else echo "Failure" && docker-compose logs test; \
 	       fi
 
+dc_perf:docker_server docker_ghz
+	cp wave.proto compose_ghz/.
+	cd compose_ghz && docker-compose up -d
+	cd compose_ghz && sleep 0.5 && while [ -z "`docker-compose ps | grep client_ghz | grep Exit`" ]; do echo "Client terminated";done
+	cd compose_ghz && \
+	    result=`docker-compose ps | grep client | grep "Exit 0"` || true && \
+	    echo "$${result}" && \
+	    if [ -n "$${result}" ]; \
+	        then echo "Success"; \
+	        else echo "Failure"; \
+	        fi \
+	    && docker-compose logs client_ghz server
+	rm compose_ghz/wave.proto
+
 dc_stop_demo:
 	cd compose_demo && docker-compose stop && docker-compose down && cd ..
 
 dc_stop_test:
 	cd compose_test && docker-compose stop && docker-compose down && cd ..
 
-dc_stop:dc_stop_demo dc_stop_test
+dc_stop_perf:
+	cd compose_ghz && docker-compose stop && docker-compose down && cd ..
+
+dc_stop:dc_stop_demo dc_stop_test dc_stop_perf
 	echo "Stopping docker compose"
 
 dc_clean:dc_stop
-	docker rmi -f docker_wave_server docker_wave_client
+	docker rmi -f docker_wave_client docker_wave_ghz docker_wave_server docker_wave_test
